# Generated by Django 5.2.7 on 2025-10-21 03:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('initial_pages', models.PositiveIntegerField()),
                ('remaining_pages', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Картридж',
                'verbose_name_plural': 'Картриджи',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Тип устройства',
                'verbose_name_plural': 'Типы устройств',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Местоположение',
                'verbose_name_plural': 'Местоположения',
            },
        ),
        migrations.CreateModel(
            name='NetworkDeviceSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ports_count', models.PositiveIntegerField(blank=True, null=True)),
                ('port_speed', models.CharField(blank=True, max_length=50)),
                ('wireless_standard', models.CharField(blank=True, max_length=50)),
                ('wireless_speed', models.CharField(blank=True, max_length=50)),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Спецификация сетевого устройства',
                'verbose_name_plural': 'Спецификации сетевых устройств',
            },
        ),
        migrations.CreateModel(
            name='PrinterScannerSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_type', models.CharField(blank=True, choices=[('laser', 'Лазерный'), ('inkjet', 'Струйный'), ('matrix', 'Матричный')], max_length=20)),
                ('color_printing', models.BooleanField(default=False)),
                ('max_resolution', models.CharField(blank=True, max_length=50)),
                ('duplex_printing', models.BooleanField(default=False)),
                ('paper_trays', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Спецификация МФУ',
                'verbose_name_plural': 'Спецификации МФУ',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Устройство', 'verbose_name_plural': 'Устройства'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
        migrations.RenameField(
            model_name='log',
            old_name='error_message',
            new_name='message',
        ),
        migrations.AddField(
            model_name='device',
            name='asset_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='qr_code_id',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='log',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='log',
            name='log_type',
            field=models.CharField(choices=[('error', 'Ошибка'), ('info', 'Информация'), ('warning', 'Предупреждение'), ('request', 'Заявка')], default='info', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='severity',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('active', 'В работе'), ('in_repair', 'В ремонте'), ('retired', 'Списано'), ('in_stock', 'На складе'), ('reserved', 'В резерве')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='CartridgeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('pages_printed_at_removal', models.PositiveIntegerField(blank=True, null=True)),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='inventory_api.cartridge')),
            ],
            options={
                'verbose_name': 'Лог использования картриджа',
                'verbose_name_plural': 'Логи использования картриджей',
            },
        ),
        migrations.CreateModel(
            name='ComputerSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(blank=True, max_length=200)),
                ('ram_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('storage_type', models.CharField(blank=True, choices=[('SSD', 'SSD'), ('HDD', 'HDD'), ('SSHD', 'SSHD')], max_length=50)),
                ('storage_capacity_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('os', models.CharField(blank=True, max_length=200)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='computer_specs', to='inventory_api.device')),
            ],
            options={
                'verbose_name': 'Спецификация ПК',
                'verbose_name_plural': 'Спецификации ПК',
            },
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='inventory_api.devicetype'),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='inventory_api.location'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['serial_number'], name='inventory_a_serial__21bff8_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='inventory_a_status_f68b48_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['location'], name='inventory_a_locatio_612766_idx'),
        ),
        migrations.AddField(
            model_name='networkdevicespecs',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network_specs', to='inventory_api.device'),
        ),
        migrations.AddField(
            model_name='printerscannerspecs',
            name='current_cartridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_in_printers', to='inventory_api.cartridge'),
        ),
        migrations.AddField(
            model_name='printerscannerspecs',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='printer_scanner_specs', to='inventory_api.device'),
        ),
        migrations.AddField(
            model_name='cartridgelog',
            name='printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartridge_logs', to='inventory_api.printerscannerspecs'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_devices',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_users', to='inventory_api.device'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
