# Generated by Django 5.2.7 on 2025-11-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0002_cartridge_devicetype_location_networkdevicespecs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('in_progress', 'В работе'), ('closed', 'Завершена'), ('cancelled', 'Отменена')], default='open', max_length=20),
        ),
    ]
