# Generated by Django 5.2.7 on 2025-11-26 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0003_log_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='severity',
            new_name='priority',
        ),
    ]
