# Generated by Django 5.2.7 on 2025-11-26 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0004_rename_severity_log_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('cpu_load', 'Загрузка ЦП (%)'), ('memory_usage', 'Использование ОЗУ (%)'), ('disk_usage', 'Использование диска (%)'), ('pages_printed', 'Отпечатано страниц'), ('temperature', 'Температура (°C)'), ('uptime', 'Время работы (сек)'), ('ping_latency', 'Задержка сети (мс)')], max_length=50)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='inventory_api.device')),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'Метрики',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'metric_type', '-timestamp'], name='inventory_a_device__b9b4ad_idx'), models.Index(fields=['timestamp'], name='inventory_a_timesta_828a07_idx')],
            },
        ),
    ]
