# Generated by Django 5.2.7 on 2026-01-27 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0006_printjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printjob',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
