# Generated by Django 5.2.7 on 2026-03-05 09:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0017_networkmapsnapshot_networkmapnode_networkmapedge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(max_length=100)),
                ('horizon', models.CharField(choices=[('24h', '24h'), ('7d', '7d'), ('30d', '30d')], max_length=20)),
                ('target_ts', models.DateTimeField()),
                ('model_kind', models.CharField(choices=[('sarima', 'SARIMA'), ('lstm', 'LSTM'), ('ensemble', 'Ensemble')], default='ensemble', max_length=20)),
                ('y_hat', models.FloatField()),
                ('p10', models.FloatField(blank=True, null=True)),
                ('p50', models.FloatField(blank=True, null=True)),
                ('p90', models.FloatField(blank=True, null=True)),
                ('alpha', models.FloatField(blank=True, null=True)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Точка прогноза',
                'verbose_name_plural': 'Точки прогноза',
                'ordering': ['-target_ts', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_kind', models.CharField(choices=[('sarima', 'SARIMA'), ('lstm', 'LSTM'), ('ensemble', 'Ensemble')], default='ensemble', max_length=20)),
                ('horizon_set', models.CharField(default='24h,7d,30d', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('quality', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Запуск прогноза',
                'verbose_name_plural': 'Запуски прогноза',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StateEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon', models.CharField(choices=[('24h', '24h'), ('7d', '7d'), ('30d', '30d')], max_length=20)),
                ('state', models.CharField(choices=[('s0', 'S0'), ('s1', 'S1'), ('s2', 'S2'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('p_s0', models.FloatField(blank=True, null=True)),
                ('p_s1', models.FloatField(blank=True, null=True)),
                ('p_s2', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Оценка состояния сервера',
                'verbose_name_plural': 'Оценки состояния сервера',
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.AddField(
            model_name='forecastpoint',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_points', to='inventory_api.device'),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_runs', to='inventory_api.device'),
        ),
        migrations.AddField(
            model_name='forecastpoint',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='inventory_api.forecastrun'),
        ),
        migrations.AddField(
            model_name='stateestimate',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_estimates', to='inventory_api.device'),
        ),
        migrations.AddField(
            model_name='stateestimate',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_estimates', to='inventory_api.forecastrun'),
        ),
        migrations.AddIndex(
            model_name='forecastrun',
            index=models.Index(fields=['device', 'model_kind', '-created_at'], name='inventory_a_device__1aaa35_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastrun',
            index=models.Index(fields=['status', '-created_at'], name='inventory_a_status_ef86ba_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastpoint',
            index=models.Index(fields=['device', 'metric_code', 'horizon', '-target_ts'], name='inventory_a_device__a62a02_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastpoint',
            index=models.Index(fields=['model_kind', 'horizon', '-target_ts'], name='inventory_a_model_k_b63315_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastpoint',
            index=models.Index(fields=['run', '-target_ts'], name='inventory_a_run_id_17941f_idx'),
        ),
        migrations.AddIndex(
            model_name='stateestimate',
            index=models.Index(fields=['device', 'horizon', '-timestamp'], name='inventory_a_device__8e27fc_idx'),
        ),
        migrations.AddIndex(
            model_name='stateestimate',
            index=models.Index(fields=['state', '-timestamp'], name='inventory_a_state_f37260_idx'),
        ),
        migrations.AddIndex(
            model_name='stateestimate',
            index=models.Index(fields=['run', '-timestamp'], name='inventory_a_run_id_98443e_idx'),
        ),
    ]
