# Generated by Django 5.2.7 on 2026-03-10 06:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0018_forecastpoint_forecastrun_stateestimate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LSTMRemoteQueueJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('submitting', 'Submitting'), ('submitted', 'Submitted'), ('polling', 'Polling'), ('retry_wait', 'RetryWait'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('remote_job_id', models.CharField(blank=True, max_length=120, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('submit_response', models.JSONField(blank=True, default=dict)),
                ('remote_snapshot', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('attempts_submit', models.PositiveIntegerField(default=0)),
                ('attempts_poll', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=5)),
                ('next_retry_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Задание очереди LSTM remote',
                'verbose_name_plural': 'Задания очереди LSTM remote',
                'ordering': ['next_retry_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='lstmremotequeuejob',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lstm_remote_jobs', to='inventory_api.device'),
        ),
        migrations.AddField(
            model_name='lstmremotequeuejob',
            name='forecast_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lstm_remote_job', to='inventory_api.forecastrun'),
        ),
        migrations.AddIndex(
            model_name='lstmremotequeuejob',
            index=models.Index(fields=['status', 'next_retry_at'], name='inventory_a_status_f9d103_idx'),
        ),
        migrations.AddIndex(
            model_name='lstmremotequeuejob',
            index=models.Index(fields=['device', '-created_at'], name='inventory_a_device__8315fb_idx'),
        ),
        migrations.AddIndex(
            model_name='lstmremotequeuejob',
            index=models.Index(fields=['remote_job_id'], name='inventory_a_remote__86a565_idx'),
        ),
    ]
