# Generated by Django 5.2.7 on 2026-03-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0019_lstmremotequeuejob_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='agentstatus',
            name='inventory_a_device__0d3b2a_idx',
        ),
        migrations.RemoveIndex(
            model_name='agentstatus',
            name='inventory_a_status__a1e6d7_idx',
        ),
        migrations.RenameIndex(
            model_name='computedmetric',
            new_name='inventory_a_device__3aa7a5_idx',
            old_name='inventory_a_device__f5590f_idx',
        ),
        migrations.RenameIndex(
            model_name='computedmetric',
            new_name='inventory_a_timesta_8711e9_idx',
            old_name='inventory_a_timesta_18a3d0_idx',
        ),
        migrations.RenameIndex(
            model_name='networkalertrule',
            new_name='inventory_a_enabled_b4b69d_idx',
            old_name='inventory_a_enabled_38fe27_idx',
        ),
        migrations.RenameIndex(
            model_name='networkalertrule',
            new_name='inventory_a_metric__ac5edc_idx',
            old_name='inventory_a_metric__c36751_idx',
        ),
        migrations.RenameIndex(
            model_name='networkmapedge',
            new_name='inventory_a_snapsho_430ed1_idx',
            old_name='inv_map_edge_ss_22024b_idx',
        ),
        migrations.RenameIndex(
            model_name='networkmapedge',
            new_name='inventory_a_snapsho_e22e37_idx',
            old_name='inv_map_edge_sd_2b76e4_idx',
        ),
        migrations.RenameIndex(
            model_name='networkmapnode',
            new_name='inventory_a_snapsho_9da3e5_idx',
            old_name='inv_map_node_sn_43af3e_idx',
        ),
        migrations.RenameIndex(
            model_name='networkmapnode',
            new_name='inventory_a_snapsho_a7d951_idx',
            old_name='inv_map_node_ip_29d2bc_idx',
        ),
        migrations.RenameIndex(
            model_name='networkmapsnapshot',
            new_name='inventory_a_is_curr_b8994a_idx',
            old_name='inv_map_snap_cur_5e0a2d_idx',
        ),
        migrations.RenameIndex(
            model_name='networkmapsnapshot',
            new_name='inventory_a_status_3760d2_idx',
            old_name='inv_map_snap_st_1a9f5f_idx',
        ),
        migrations.RenameIndex(
            model_name='rawmetric',
            new_name='inventory_a_device__5ac4aa_idx',
            old_name='inventory_a_device__70bfa9_idx',
        ),
        migrations.RenameIndex(
            model_name='rawmetric',
            new_name='inventory_a_timesta_b66f69_idx',
            old_name='inventory_a_timesta_0fc879_idx',
        ),
    ]
