# Generated by Django 5.2.7 on 2026-03-15 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0020_remove_agentstatus_inventory_a_device__0d3b2a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('constraints_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Альтернатива КСППР',
                'verbose_name_plural': 'Альтернативы КСППР',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='inventory_a_code_904743_idx'), models.Index(fields=['is_active'], name='inventory_a_is_acti_fa0a31_idx')],
            },
        ),
        migrations.CreateModel(
            name='DecisionCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Критерий КСППР',
                'verbose_name_plural': 'Критерии КСППР',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='inventory_a_code_e3f7be_idx'), models.Index(fields=['is_active'], name='inventory_a_is_acti_9febbc_idx')],
            },
        ),
        migrations.CreateModel(
            name='DecisionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('device_type', 'DeviceType'), ('device', 'Device')], default='global', max_length=20)),
                ('horizon', models.CharField(choices=[('24h', '24h'), ('7d', '7d'), ('30d', '30d')], default='24h', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_policies_created', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_policies', to='inventory_api.device')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_policies', to='inventory_api.devicetype')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='inventory_api.decisionpolicy')),
            ],
            options={
                'verbose_name': 'Политика КСППР',
                'verbose_name_plural': 'Политики КСППР',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionPolicyAHPPairwise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterion_i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ahp_as_i', to='inventory_api.decisioncriterion')),
                ('criterion_j', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ahp_as_j', to='inventory_api.decisioncriterion')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ahp_pairwise', to='inventory_api.decisionpolicy')),
            ],
            options={
                'verbose_name': 'AHP парное сравнение',
                'verbose_name_plural': 'AHP парные сравнения',
                'ordering': ['policy_id', 'criterion_i_id', 'criterion_j_id'],
            },
        ),
        migrations.CreateModel(
            name='DecisionPolicyLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss_s0', models.FloatField(default=0.0)),
                ('loss_s1', models.FloatField(default=0.0)),
                ('loss_s2', models.FloatField(default=0.0)),
                ('fixed_cost', models.FloatField(default=0.0)),
                ('downtime_minutes', models.FloatField(default=0.0)),
                ('ops_effort', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_losses', to='inventory_api.decisionaction')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss_rows', to='inventory_api.decisionpolicy')),
            ],
            options={
                'verbose_name': 'Матрица потерь КСППР',
                'verbose_name_plural': 'Матрицы потерь КСППР',
                'ordering': ['policy_id', 'action_id'],
            },
        ),
        migrations.CreateModel(
            name='DecisionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon', models.CharField(default='24h', max_length=20)),
                ('mode', models.CharField(choices=[('bayes', 'Bayes'), ('advanced', 'Bayes+AHP')], default='bayes', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('risk_snapshot', models.JSONField(blank=True, default=dict)),
                ('explanation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_runs_created', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_runs', to='inventory_api.device')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_runs', to='inventory_api.decisionpolicy')),
                ('recommended_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_runs', to='inventory_api.decisionaction')),
            ],
            options={
                'verbose_name': 'Запуск КСППР',
                'verbose_name_plural': 'Запуски КСППР',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_state', models.CharField(choices=[('s0', 'S0'), ('s1', 'S1'), ('s2', 'S2'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('outage_minutes', models.FloatField(default=0.0)),
                ('incident_cost', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actual_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_items', to='inventory_api.decisionaction')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_feedback_created', to=settings.AUTH_USER_MODEL)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='inventory_api.decisionrun')),
            ],
            options={
                'verbose_name': 'Обратная связь КСППР',
                'verbose_name_plural': 'Обратная связь КСППР',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionRunAHP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.JSONField(blank=True, default=dict)),
                ('lambda_max', models.FloatField(default=0.0)),
                ('ci', models.FloatField(default=0.0)),
                ('cr', models.FloatField(default=0.0)),
                ('is_consistent', models.BooleanField(default=False)),
                ('matrix', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ahp', to='inventory_api.decisionrun')),
            ],
            options={
                'verbose_name': 'AHP результат запуска КСППР',
                'verbose_name_plural': 'AHP результаты запусков КСППР',
            },
        ),
        migrations.CreateModel(
            name='DecisionRunScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_loss', models.FloatField(default=0.0)),
                ('bayes_utility', models.FloatField(default=0.0)),
                ('ahp_utility', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('is_recommended', models.BooleanField(default=False)),
                ('explanation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_scores', to='inventory_api.decisionaction')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='inventory_api.decisionrun')),
            ],
            options={
                'verbose_name': 'Оценка альтернативы КСППР',
                'verbose_name_plural': 'Оценки альтернатив КСППР',
                'ordering': ['run_id', 'rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DecisionRunUtility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility', models.FloatField(default=0.0)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_utilities', to='inventory_api.decisionaction')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_utilities', to='inventory_api.decisioncriterion')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_utilities', to='inventory_api.decisionrun')),
            ],
            options={
                'verbose_name': 'Локальная полезность критерия',
                'verbose_name_plural': 'Локальные полезности критериев',
                'ordering': ['run_id', 'action_id', 'criterion_id'],
            },
        ),
        migrations.AddIndex(
            model_name='decisionpolicy',
            index=models.Index(fields=['scope', 'horizon', 'is_active'], name='inventory_a_scope_c6fb31_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionpolicy',
            index=models.Index(fields=['device_type', 'horizon', 'is_active'], name='inventory_a_device__19875c_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionpolicy',
            index=models.Index(fields=['device', 'horizon', 'is_active'], name='inventory_a_device__d7e3d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='decisionpolicy',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='uniq_decision_policy_name_version'),
        ),
        migrations.AddConstraint(
            model_name='decisionpolicyahppairwise',
            constraint=models.UniqueConstraint(fields=('policy', 'criterion_i', 'criterion_j'), name='uniq_decision_policy_ahp_pair'),
        ),
        migrations.AddConstraint(
            model_name='decisionpolicyloss',
            constraint=models.UniqueConstraint(fields=('policy', 'action'), name='uniq_decision_policy_action'),
        ),
        migrations.AddIndex(
            model_name='decisionrun',
            index=models.Index(fields=['device', 'horizon', '-created_at'], name='inventory_a_device__53362b_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionrun',
            index=models.Index(fields=['mode', '-created_at'], name='inventory_a_mode_1a1f89_idx'),
        ),
        migrations.AddConstraint(
            model_name='decisionrunscore',
            constraint=models.UniqueConstraint(fields=('run', 'action'), name='uniq_decision_run_action'),
        ),
        migrations.AddConstraint(
            model_name='decisionrunutility',
            constraint=models.UniqueConstraint(fields=('run', 'action', 'criterion'), name='uniq_decision_run_action_criterion'),
        ),
    ]
