# Generated by Django 5.2.7 on 2026-03-17 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0021_decisionaction_decisioncriterion_decisionpolicy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decisionaction',
            options={'ordering': ['name'], 'verbose_name': 'Альтернатива СППР', 'verbose_name_plural': 'Альтернативы СППР'},
        ),
        migrations.AlterModelOptions(
            name='decisioncriterion',
            options={'ordering': ['name'], 'verbose_name': 'Критерий СППР', 'verbose_name_plural': 'Критерии СППР'},
        ),
        migrations.AlterModelOptions(
            name='decisionfeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Обратная связь СППР', 'verbose_name_plural': 'Обратная связь СППР'},
        ),
        migrations.AlterModelOptions(
            name='decisionpolicy',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Политика СППР', 'verbose_name_plural': 'Политики СППР'},
        ),
        migrations.AlterModelOptions(
            name='decisionpolicyloss',
            options={'ordering': ['policy_id', 'action_id'], 'verbose_name': 'Матрица потерь СППР', 'verbose_name_plural': 'Матрицы потерь СППР'},
        ),
        migrations.AlterModelOptions(
            name='decisionrun',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запуск СППР', 'verbose_name_plural': 'Запуски СППР'},
        ),
        migrations.AlterModelOptions(
            name='decisionrunahp',
            options={'verbose_name': 'AHP результат запуска СППР', 'verbose_name_plural': 'AHP результаты запусков СППР'},
        ),
        migrations.AlterModelOptions(
            name='decisionrunscore',
            options={'ordering': ['run_id', 'rank', 'id'], 'verbose_name': 'Оценка альтернативы СППР', 'verbose_name_plural': 'Оценки альтернатив СППР'},
        ),
    ]
