# Generated by Django 5.2.7 on 2026-03-17 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0022_alter_decisionaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StateInferenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('thresholds', models.JSONField(blank=True, default=dict)),
                ('risk_ratio_baseline', models.FloatField(default=0.75)),
                ('risk_ratio_scale', models.FloatField(default=0.75)),
                ('medium_risk_level', models.FloatField(default=0.4)),
                ('critical_risk_level', models.FloatField(default=0.85)),
                ('overall_hint_weight', models.FloatField(default=0.25)),
                ('s0_bias', models.FloatField(default=0.15)),
                ('s0_effective_weight', models.FloatField(default=0.85)),
                ('s0_avg_weight', models.FloatField(default=0.45)),
                ('s0_medium_weight', models.FloatField(default=0.35)),
                ('s0_critical_weight', models.FloatField(default=0.55)),
                ('s1_bias', models.FloatField(default=0.1)),
                ('s1_avg_weight', models.FloatField(default=0.9)),
                ('s1_medium_weight', models.FloatField(default=0.45)),
                ('s1_markov_weight', models.FloatField(default=0.1)),
                ('s2_bias', models.FloatField(default=0.05)),
                ('s2_effective_power', models.FloatField(default=1.6)),
                ('s2_critical_weight', models.FloatField(default=0.3)),
                ('s2_medium_weight', models.FloatField(default=0.15)),
                ('s2_markov_weight', models.FloatField(default=0.1)),
                ('confidence_max', models.FloatField(default=0.98)),
                ('confidence_base', models.FloatField(default=0.36)),
                ('confidence_component_weight', models.FloatField(default=0.08)),
                ('confidence_feature_weight', models.FloatField(default=0.07)),
                ('confidence_margin_weight', models.FloatField(default=0.35)),
                ('confidence_component_cap', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_inference_profiles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль модели состояния',
                'verbose_name_plural': 'Профили модели состояния',
                'ordering': ['-is_active', '-updated_at', '-id'],
                'indexes': [models.Index(fields=['is_active', '-updated_at'], name='inventory_a_is_acti_97fd3d_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='uniq_state_inference_profile_name_version')],
            },
        ),
    ]
