# Generated by Django 5.2.7 on 2026-03-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0023_stateinferenceprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateinferenceprofile',
            name='score_weights',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='stateinferenceprofile',
            name='softmax_temperature',
            field=models.FloatField(default=1.0),
        ),
    ]
