# Generated by Django 5.2.7 on 2026-03-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0024_stateinferenceprofile_score_weights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateinferenceprofile',
            name='forecast_metric_controls',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
