# Generated by Django 5.2.7 on 2026-04-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_api", "0025_stateinferenceprofile_forecast_metric_controls"),
    ]

    operations = [
        migrations.AddField(
            model_name="stateinferenceprofile",
            name="orchestrator_controls",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
