# Generated by Django 5.2.7 on 2026-05-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory_api', '0027_applicationupdatejob'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('section', models.CharField(default='main', max_length=80)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveIntegerField(default=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Правило доступа к странице',
                'verbose_name_plural': 'Правила доступа к страницам',
                'ordering': ['section', 'order', 'label'],
            },
        ),
        migrations.RenameIndex(
            model_name='applicationupdatejob',
            new_name='inventory_a_status_6c28d9_idx',
            old_name='inventory_a_status_4c75a2_idx',
        ),
        migrations.RenameIndex(
            model_name='applicationupdatejob',
            new_name='inventory_a_target__f60553_idx',
            old_name='inventory_a_target__c60357_idx',
        ),
        migrations.AddField(
            model_name='pageaccessrule',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='page_access_rules', to='auth.group'),
        ),
        migrations.AddIndex(
            model_name='pageaccessrule',
            index=models.Index(fields=['route_name'], name='inventory_a_route_n_1a0f56_idx'),
        ),
        migrations.AddIndex(
            model_name='pageaccessrule',
            index=models.Index(fields=['section', 'order'], name='inventory_a_section_18e61e_idx'),
        ),
        migrations.AddIndex(
            model_name='pageaccessrule',
            index=models.Index(fields=['is_enabled'], name='inventory_a_is_enab_85d9d9_idx'),
        ),
    ]
