# Generated by Django 5.2.7 on 2026-05-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0028_page_access_rule'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='forecastpoint',
            index=models.Index(fields=['device', 'run', 'model_kind', 'horizon', 'target_ts'], name='fpoint_dev_run_kind_h_ts'),
        ),
        migrations.AddIndex(
            model_name='forecastpoint',
            index=models.Index(fields=['run', 'model_kind', 'horizon', 'metric_code', 'target_ts'], name='fpoint_run_kind_h_metric'),
        ),
        migrations.AddIndex(
            model_name='rawmetric',
            index=models.Index(fields=['device', 'code', 'timestamp', 'id'], name='rawmetric_dev_code_ts_id'),
        ),
    ]
