[DEFAULT]
# Пример: http://server:8000/api/
ApiUrl = http://10.250.0.84:8080/api/
Token = 151085d1061d9c142a9336df35a5f8e395d9f1a7

# Если нужно отправлять serial_number устройства (не рекомендуется для печати)
SendSerial = 0
SerialNumber = AUTO

# Как часто обновлять карту принтеров -> IP (сек)
PrinterMapRefreshSec = 300
